[project]
name = "focushub-narration"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.9,<3.12"
dependencies = [
    "TTS>=0.22.0",
    "pedalboard>=0.9.0",
    "soundfile>=0.13.1",
    "torch>=2.1.0",
    "transformers>=4.33.0,<4.34.0",
    "torchcodec",
]

[tool.ruff]
line-length = 100
target-version = "py312"

[tool.ruff.lint]
# Enable Pyflakes (F), Pycodestyle (E, W), isort (I), and Flake8-bugbear (B)
select = ["E", "F", "W", "I", "B"]
ignore = []

[tool.ruff.format]
quote-style = "double"
indent-style = "space"
skip-magic-trailing-comma = false
line-ending = "auto"

[dependency-groups]
dev = [
    "ruff>=0.15.14",
]

